### ISSUE TITLE
Travis CI not running: Expected — Waiting for status to be reported.

### ISSUE THREAD

**Issue by musicinmybrain** [faucetsdn/ryu#123]
I am working on a [draft PR](https://github.com/faucetsdn/ryu/pull/122) for msgpack 1.0 support, and in the past couple of days Travis CI has stopped working. It hangs in the _Expected — Waiting for status to be reported_ state. Is there a known issue?

**Comment by anarkiwi** [comment]
Apologies for the delay. Travis has moved to a new pricing plan (https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing), so we have been moving to GitHub actions instead (we have very basic support for GHA now in). If you merge up your branch this issue should be resolved now - please reopen this issue if it is not.
